In [1]:
import pandas as pd
import numpy as np

In [2]:
ml = [1,2,3]

In [3]:
a1 = np.array(ml)
a1

array([1, 2, 3])

In [4]:
ml = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(ml)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np1 = np.arange(1,11,1)
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.37207187, 0.71930153, 0.26002764, 0.59127967, 0.76999806])

In [15]:
np.random.rand(3,3)

array([[0.14876595, 0.16275709, 0.83332689],
       [0.87228518, 0.36729189, 0.6210687 ],
       [0.72103328, 0.33333008, 0.65481377]])

In [16]:
np.random.randn(3)

array([-1.4119622 , -0.81060389, -2.17805257])

In [17]:
np.random.randn(5)

array([ 0.95907119,  0.15386996,  2.32691167,  0.44455726, -2.2687344 ])

In [18]:
np.random.randn(4,4)

array([[-0.21746192,  0.55840186,  3.19041218, -1.03214375],
       [ 0.97531282,  0.89536029,  1.71905747, -0.61863231],
       [ 1.0417765 , -1.76666921, -1.48819821,  0.99246497],
       [ 0.73953152,  1.17684687,  0.30764388,  1.13164069]])

In [19]:
np.random.randint(1,10,5)

array([3, 8, 2, 4, 6])

In [20]:
np.random.randint(1,100,10)

array([44, 63,  4, 78, 45,  8, 42, 78, 40, 67])

In [21]:
a2 = np.arange(25)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ra2 = np.random.randint(0,50,10) 
ra2

array([29, 28,  3, 49, 16, 43,  2, 27, 28, 14])

In [23]:
a2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ra2.reshape(5,2)

array([[29, 28],
       [ 3, 49],
       [16, 43],
       [ 2, 27],
       [28, 14]])

In [25]:
np.max(ra2)

49

In [26]:
np.min(ra2)

2

In [27]:
np.argmax(ra2)

3

In [28]:
np.argmin(ra2)

6

In [29]:
ra2.shape

(10,)

In [30]:
ra2.dtype

dtype('int32')

In [31]:
type(ra2)

numpy.ndarray

In [32]:
np1 = np.arange(1,21,2)
np1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [33]:
np1[2:5]

array([5, 7, 9])

In [34]:
np1[7:]

array([15, 17, 19])

In [35]:
np1[1:5] = 100

In [36]:
np1

array([  1, 100, 100, 100, 100,  11,  13,  15,  17,  19])

In [37]:
np1_copy= np1.copy()
np1_copy

array([  1, 100, 100, 100, 100,  11,  13,  15,  17,  19])

In [38]:
np1_copy[4:]= 99
np1_copy

array([  1, 100, 100, 100,  99,  99,  99,  99,  99,  99])

In [39]:
np1

array([  1, 100, 100, 100, 100,  11,  13,  15,  17,  19])

In [40]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a2[1]

array([4, 5, 6])

In [42]:
a2[1,1]

5

In [43]:
a2[2,2]

9

In [44]:
a2[1:,1:]

array([[5, 6],
       [8, 9]])

In [45]:
a22 = a2 > 1
a22

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [46]:
a22[a2>1]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [47]:
an2 = np.arange(50).reshape(5,10)
an2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
an2[2:4, 5:7]

array([[25, 26],
       [35, 36]])

In [49]:
a4 = np.arange(0,11)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
a4 + a4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
a4/a4

<ipython-input-51-6e7cf59c888e>:1: RuntimeWarning: invalid value encountered in true_divide
  a4/a4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [52]:
a4-a4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
a4*a4

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
a4 +30

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [55]:
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
a4//2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [57]:
a4 % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [58]:
a4**5

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000], dtype=int32)

In [59]:
np.sqrt(a4)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
np.exp(a4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [61]:
np.sin(a4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [62]:
np.log(a4)

<ipython-input-62-ba49b63410f2>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a4)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [63]:
abs(a4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a5= np.arange(-10,10)
a5

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [65]:
np.abs(a5)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])