In [1]:
import pandas as pd
import numpy as np

In [2]:
ml = [1,2,3]

In [5]:
a1 = np.array(ml)
a1

array([1, 2, 3])

In [6]:
ml = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(ml)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np1 = np.arange(1,11,1)
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [12]:
np.zeros(2)

array([0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [24]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.random.rand(5)

array([0.52181636, 0.46675461, 0.05740106, 0.60498832, 0.26868332])

In [30]:
np.random.rand(3,3)

array([[0.06981146, 0.67018365, 0.53347275],
       [0.97890357, 0.17962384, 0.06764159],
       [0.12939651, 0.14542787, 0.36522061]])

In [31]:
np.random.randn(3)

array([ 0.8322607 ,  0.16509871, -1.40473157])

In [33]:
np.random.randn(5)

array([ 1.21335196,  0.47905617,  0.02237418, -0.23628469,  0.81665338])

In [39]:
np.random.randn(4,4)

array([[ 0.74770595, -0.14311574,  0.70979133,  0.90852264],
       [-0.14176267, -1.45236844,  1.02368025, -1.09889122],
       [-0.9452029 ,  0.10321367,  2.22837267, -0.26114081],
       [ 0.19347306, -0.33909393,  0.0781396 , -0.05500975]])

In [37]:
np.random.randint(1,10,5)

array([9, 8, 5, 7, 1])

In [40]:
np.random.randint(1,100,10)

array([99, 77, 77, 14, 35, 49, 47, 59, 83, 22])

In [42]:
a2 = np.arange(25)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ra2 = np.random.randint(0,50,10) 
ra2

array([37,  9, 14, 44, 30, 34, 19,  3, 16, 14])

In [45]:
a2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ra2.reshape(5,2)

array([[37,  9],
       [14, 44],
       [30, 34],
       [19,  3],
       [16, 14]])

In [47]:
np.max(ra2)

44

In [48]:
np.min(ra2)

3

In [49]:
np.argmax(ra2)

3

In [50]:
np.argmin(ra2)

7

In [51]:
ra2.shape

(10,)

In [52]:
ra2.dtype

dtype('int32')

In [53]:
type(ra2)

numpy.ndarray